# Generated by Django 3.1.2 on 2021-04-12 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True, null=True)),
                ('time_added', models.DateField()),
                ('last_edit', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
